name: v10
# run workflow on git push and git pull
on: [push, pull_request]
jobs:
  cypress-run:
    # OS
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        # checks-out your repository so your workflow can access it
        # uses: actions/checkout@v2
      # - name: Configure Cypress for dashboard
        run: |
           npm install
           npx cypress run --record --key 35447304-b1bd-474a-a624-131a4da21d29
      - name: Run Cypress Tests
        # GitHub Action for running Cypress end-to-end tests
        uses: cypress-io/github-action@v4
        with:
          config-file: cypress.config.js
